events {
    worker_connections 1024;
}

http {
    # هادي ضرورية باش الـ CSS يرجع يتشارجا بالألوان ديالو بلا ما يتبلوكا ف المتصفح
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80; # الـ Port الداخلي الصحيح

        # 1. الـ WordPress
        location / {
            resolver 127.0.0.11 valid=5s;
            set $upstream_wp http://web_voip_tf:80;
            proxy_pass $upstream_wp;

            # عطيناه الـ 8080 هنا حيت الـ WordPress كيحتاجها باش يبني الـ Links ديال الـ CSS صحاح
            proxy_set_header Host $host:8080;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect off;
        }

        # 2. الـ Alertmanager 
        location /alertmanager/ {
            resolver 127.0.0.11 valid=5s;
            set $upstream_alert http://alertmanager:9093; 
            proxy_pass $upstream_alert/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
