global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'discord'

receivers:
- name: 'discord'
  discord_configs:
  - webhook_url: 'https://discordapp.com/api/webhooks/1523633593908330700/uf-cQ4JS475uav9gYD4bDc8_mQunU4SDuu-UjHZqRoYz7m_6gMOb33Md9l2OlBVXSCXs'
    send_resolved: true
