server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://web_voip:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # زيادة الـ Timeouts لتجنب الـ 502 Gateway Timeout
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
    }

    # إضافة إعداد خاص للـ Grafana باش يخدم بـ WebSocket بلا مشاكل
    location /grafana/ {
        proxy_pass http://grafana:3000/;
        proxy_set_header Host $host;
    }
}
