---
- name: Post-Deployment System Optimization and Hardening
  hosts: aws_servers
  become: true

  tasks:
    - name: 1. Mettre à jour le cache APT (apt update)
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: 2. Nettoyer les packages obsolètes (apt autoremove)
      apt:
        autoremove: yes
        purge: yes

    - name: 3. Libérer de l'espace Docker (Docker System Prune)
      command: docker system prune -a --force
      changed_when: false

    - name: 4. Vérifier le statut des conteneurs de l'infrastructure
      command: "{% raw %}docker ps --format 'table {{.Names}}\t{{.Status}}'{% endraw %}"
      register: docker_status
      changed_when: false

    - name: 5. Afficher le rapport final dans le terminal
      debug:
        msg: "{{ docker_status.stdout_lines }}"

    - name: 6. Envoyer le rapport à Discord
      uri:
        url: "https://discordapp.com/api/webhooks/1524058502673334422/Lm16H7MdHhrkhjyOyGqoKFDmKRoASqwYGJ31IjlNp6DZEUtwxNcoi2zkTEpotTsOiaN6"
        method: POST
        body_format: json
        body:
          username: "Ansible Bot"
          avatar_url: "https://ansible.com/favicon.ico"
          content: "📊 **Rapport de Maintenance Ansible (AWS Cloud)**\n```text\n{{ docker_status.stdout }}\n```"
        status_code: 204
